apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-cfg
  # this config map could also live in the default namespace and be referenced
  # through `downstreamResources` in fleet.yaml, with the corresponding experimental
  # feature enabled in Fleet.
  namespace: fleet-local
data:
  values.yaml:
    replicas: 1
    debug: true
{{- with (index (lookup "v1" "Service" "kube-system" "traefik").status.loadBalancer.ingress 0) }}
    hostname: {{ .ip }}.sslip.io
{{- end }}


