apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-cfg
data:
  values.yaml:
    replicas: 1
    debug: true
    {{- with (index (lookup "v1" "Service" "kube-system" "traefik").status.loadBalancer.ingress 0) }}
    hostname: "{{ .ip }}.sslip.io"
    {{- end }}


