apiVersion: v1
kind: Service
metadata:
  name: fake-slow-registry-service
spec:
  selector:
    app: fake-slow-registry
  ports:
    - protocol: TCP
      port: 4242        # Port exposed by the Service
      targetPort: 8080  # Port the container is listening on
  type: ClusterIP
